# frozen_string_literal: true

require_relative "test_helper"

class EmitterTest < Minitest::Test
  include RuriTestHelpers

  def test_emits_exact_expected_output_for_hello_world
    expected = <<~ELISP
      ;;; -*- lexical-binding: t; -*-
      ;;; Generated by ruri #{Ruri::VERSION} from test.ruri. DO NOT EDIT.

      (defun hello-buffer ()
        (interactive)
        (with-current-buffer "*scratch*"
          (insert "Hello from Ruby syntax!\\n")))
    ELISP

    assert_equal expected, Ruri.compile(HELLO_SOURCE, path: "test.ruri")
  end

  def test_multiple_commands_are_separated_by_blank_lines
    output = Ruri.compile(<<~RURI, path: "test.ruri")
      command :first_cmd do
        interactive
        insert("one")
      end

      command :second_cmd do
        interactive
        insert("two")
      end
    RURI

    assert_includes output, "(defun first-cmd ()\n  (interactive)\n  (insert \"one\"))\n\n(defun second-cmd ()"
  end

  def test_command_with_only_interactive_closes_on_same_line
    output = Ruri.compile(<<~RURI, path: "test.ruri")
      command :noop_cmd do
        interactive
      end
    RURI

    assert_includes output, "(defun noop-cmd ()\n  (interactive))"
  end

  def test_nested_buffer_blocks_indent_each_level
    output = Ruri.compile(<<~RURI, path: "test.ruri")
      command :nested_cmd do
        interactive
        with_current_buffer("*scratch*") do
          with_current_buffer("*Messages*") do
            insert("deep")
          end
        end
      end
    RURI

    assert_includes output, <<~'ELISP'.chomp
      (with-current-buffer "*scratch*"
          (with-current-buffer "*Messages*"
            (insert "deep")))
    ELISP
  end

  def test_escapes_lisp_special_characters
    output = Ruri.compile(<<~'RURI', path: "test.ruri")
      command :escape_cmd do
        interactive
        insert("quote\"back\\slash\nnewline\ttab")
      end
    RURI

    assert_includes output, '(insert "quote\"back\\\\slash\nnewline\ttab")'
  end

  def test_escapes_control_characters_as_three_digit_octal
    output = Ruri.compile(<<~'RURI', path: "test.ruri")
      command :ctrl_cmd do
        interactive
        insert("a\u0001b\u007Fc\u0000d\u001Be")
      end
    RURI

    assert_includes output, '(insert "a\001b\177c\000d\ee")'
  end

  def test_octal_escapes_are_three_digits
    # A following literal digit must not join the escape.
    text = "\u0001" + "5"
    forms = [Ruri::Forms::Command.new(
      source_name: "octal_cmd",
      name: "octal-cmd",
      body: [Ruri::Forms::Interactive.new, Ruri::Forms::Insert.new(text: text)]
    )]

    output = Ruri::Emitter.emit(forms, source_path: "test.ruri")

    assert_includes output, '(insert "\0015")'
  end

  def test_unicode_passes_through_as_utf8
    output = Ruri.compile(<<~RURI, path: "test.ruri")
      command :uni_cmd do
        interactive
        insert("こんにちは 🌸 瑠璃")
      end
    RURI

    assert_includes output, '(insert "こんにちは 🌸 瑠璃")'
    assert output.encoding == Encoding::UTF_8
  end

  def test_output_is_deterministic
    one = Ruri.compile(HELLO_SOURCE, path: "test.ruri")
    two = Ruri.compile(HELLO_SOURCE, path: "test.ruri")

    assert_equal one, two
  end

  def test_output_starts_with_lexical_binding_line
    output = Ruri.compile(HELLO_SOURCE, path: "test.ruri")

    assert output.start_with?(";;; -*- lexical-binding: t; -*-\n")
    assert_includes output, "from test.ruri"
  end
end
