# frozen_string_literal: true

require_relative "test_helper"

class EmitterTest < Minitest::Test
  include RuriTestHelpers

  def test_emits_exact_expected_output_for_hello_world
    expected = <<~ELISP
      ;;; -*- lexical-binding: t; -*-
      ;;; Generated by ruri #{Ruri::VERSION} from test.ruri. DO NOT EDIT.

      (defun hello-buffer ()
        (interactive)
        (with-current-buffer "*scratch*"
          (insert "Hello from Ruby syntax!\\n")))
    ELISP

    assert_equal expected, Ruri.compile(HELLO_SOURCE, path: "test.ruri")
  end

  def test_multiple_commands_are_separated_by_blank_lines
    output = Ruri.compile(<<~RURI, path: "test.ruri")
      command :first_cmd do
        interactive
        insert("one")
      end

      command :second_cmd do
        interactive
        insert("two")
      end
    RURI

    assert_includes output, "(defun first-cmd ()\n  (interactive)\n  (insert \"one\"))\n\n(defun second-cmd ()"
  end

  def test_command_with_only_interactive_closes_on_same_line
    output = Ruri.compile(<<~RURI, path: "test.ruri")
      command :noop_cmd do
        interactive
      end
    RURI

    assert_includes output, "(defun noop-cmd ()\n  (interactive))"
  end

  def test_nested_buffer_blocks_indent_each_level
    output = Ruri.compile(<<~RURI, path: "test.ruri")
      command :nested_cmd do
        interactive
        with_current_buffer("*scratch*") do
          with_current_buffer("*Messages*") do
            insert("deep")
          end
        end
      end
    RURI

    assert_includes output, <<~'ELISP'.chomp
      (with-current-buffer "*scratch*"
          (with-current-buffer "*Messages*"
            (insert "deep")))
    ELISP
  end

  def test_escapes_lisp_special_characters
    output = Ruri.compile(<<~'RURI', path: "test.ruri")
      command :escape_cmd do
        interactive
        insert("quote\"back\\slash\nnewline\ttab")
      end
    RURI

    assert_includes output, '(insert "quote\"back\\\\slash\nnewline\ttab")'
  end

  def test_escapes_control_characters_as_three_digit_octal
    output = Ruri.compile(<<~'RURI', path: "test.ruri")
      command :ctrl_cmd do
        interactive
        insert("a\u0001b\u007Fc\u0000d\u001Be")
      end
    RURI

    assert_includes output, '(insert "a\001b\177c\000d\ee")'
  end

  def test_octal_escapes_are_three_digits
    # A following literal digit must not join the escape.
    text = "\u0001" + "5"
    forms = [Ruri::Forms::Command.new(
      source_name: "octal_cmd",
      name: "octal-cmd",
      parameters: Ruri::Forms::ParameterList.new(required: [], optionals: [], rest: nil),
      body: [Ruri::Forms::Interactive.new(spec: nil), Ruri::Forms::Insert.new(text: text)]
    )]

    output = Ruri::Emitter.emit(forms, source_path: "test.ruri")

    assert_includes output, '(insert "\0015")'
  end

  def test_unicode_passes_through_as_utf8
    output = Ruri.compile(<<~RURI, path: "test.ruri")
      command :uni_cmd do
        interactive
        insert("こんにちは 🌸 瑠璃")
      end
    RURI

    assert_includes output, '(insert "こんにちは 🌸 瑠璃")'
    assert output.encoding == Encoding::UTF_8
  end

  def test_output_is_deterministic
    one = Ruri.compile(HELLO_SOURCE, path: "test.ruri")
    two = Ruri.compile(HELLO_SOURCE, path: "test.ruri")

    assert_equal one, two
  end

  def test_output_starts_with_lexical_binding_line
    output = Ruri.compile(HELLO_SOURCE, path: "test.ruri")

    assert output.start_with?(";;; -*- lexical-binding: t; -*-\n")
    assert_includes output, "from test.ruri"
  end

  def test_source_path_cannot_add_lines_to_generated_lisp
    path = "safe.ruri\n(error \"injected\")\t"

    output = Ruri.compile(HELLO_SOURCE, path: path)

    assert_includes output, "from safe.ruri\\n(error \"injected\")\\t. DO NOT EDIT."
    assert_equal(1, output.lines.count { |line| line.include?("injected") })
    refute(output.lines.any? { |line| line.start_with?("(error") })
  end

  def test_emits_generic_elisp_calls_and_literals
    output = Ruri.compile(<<~RURI, path: "expressions.ruri")
      command :expression_cmd do
        interactive
        el.message("buffer: %s", el.buffer_name, 42, 1.5, true, false, nil,
                   :after_save_hook, [1, :x])
      end
    RURI

    assert_includes output, <<~ELISP.chomp
      (message "buffer: %s"
          (buffer-name)
          42 1.5 t nil nil 'after-save-hook
          (vector 1 'x))
    ELISP
  end

  def test_emits_hygienic_lexical_locals_and_conditionals
    output = Ruri.compile(<<~RURI, path: "locals.ruri")
      command :choose do
        interactive
        case_fold_search = el.buffer_modified_p
        if case_fold_search
          el.message("changed")
        else
          el.message("clean")
        end
        unless case_fold_search
          el.message("unchanged")
        end
      end
    RURI

    assert_includes output, "(let (ruri--local-case-fold-search)"
    assert_includes output, "(setq ruri--local-case-fold-search"
    assert_includes output, "(if ruri--local-case-fold-search"
    assert_includes output, "(not ruri--local-case-fold-search)"
    refute_includes output, "(let (case-fold-search)"
  end

  def test_emits_generic_elisp_body_forms
    output = Ruri.compile(<<~RURI, path: "blocks.ruri")
      command :preserve_point do
        interactive
        el.save_excursion do
          position = el.point
          el.goto_char(el.point_min)
          el.insert(el.number_to_string(position))
        end
      end
    RURI

    assert_includes output, "(let (ruri--local-position)"
    assert_includes output, "(save-excursion"
    assert_includes output, "(setq ruri--local-position"
    assert_includes output, "(goto-char"
  end

  def test_emits_lambdas_and_named_function_values
    output = Ruri.compile(<<~RURI, path: "callbacks.ruri")
      command :callbacks do
        interactive
        prefix = "<"
        callback = fn do |value|
          el.concat(prefix, value, ">")
        end
        el.mapcar(callback, ["a", "b"])
        el.add_hook(:after_save_hook, function(:callbacks))
      end
    RURI

    assert_includes output, "(lambda (ruri--local-value)"
    assert_includes output,
                    '(concat ruri--local-prefix ruri--local-value ">")'
    assert_includes output, "(function callbacks)"
  end

  def test_emits_lists_cons_quote_and_quasiquote
    output = Ruri.compile(<<~RURI, path: "data.ruri")
      command :data do
        interactive
        tail = list("b", "c")
        pair = quote(cons(:key, :value))
        template = quasiquote(list(:head, unquote(el.upcase("x")), splice(tail)))
        el.message("%S %S", pair, template)
      end
    RURI

    assert_includes output, '(list "b" "c")'
    assert_includes output, "'(key . value)"
    assert_includes output, "`(head"
    assert_includes output, ',(upcase "x")'
    assert_includes output, ",@ruri--local-tail"
  end

  def test_emits_ruby_operators_and_loops
    output = Ruri.compile(<<~RURI, path: "loops.ruri")
      command :loops do
        interactive
        count = 0
        while count < 2 && !false
          count = count + 1
        end
        until count >= 3
          count = count + 1
        end
        list(1, 2).each do |item|
          count = count + item
        end
        el.message("%S", count != 6 || false)
      end
    RURI

    assert_includes output, "(and"
    assert_includes output, "(< ruri--local-count 2)"
    assert_includes output, "(not nil)"
    assert_includes output, "(while"
    assert_includes output, "(mapc"
    assert_includes output, "(lambda (ruri--local-item)"
    assert_includes output, "(not\n"
    assert_includes output, "(equal ruri--local-count 6)"
  end

  def test_emits_top_level_function_definitions
    output = Ruri.compile(<<~RURI, path: "functions.ruri")
      function :factorial do |number|
        if number <= 1
          1
        else
          number * el.factorial(number - 1)
        end
      end

      function :decorate do |value|
        prefix = "<"
        el.concat(prefix, value, ">")
      end
    RURI

    assert_includes output, "(defun factorial (ruri--local-number)"
    assert_includes output, "(* ruri--local-number"
    assert_includes output, "(factorial"
    assert_includes output, "(defun decorate (ruri--local-value)"
    assert_includes output, "(let (ruri--local-prefix)"
    assert_includes output, '(concat ruri--local-prefix ruri--local-value ">")'
  end

  def test_docstring_renders_on_its_own_line
    output = Ruri.compile(<<~RURI, path: "test.ruri")
      command :greet_cmd do
        doc "Greet the world."
        interactive
        insert("hi")
      end
    RURI

    assert_includes output, <<~ELISP
      (defun greet-cmd ()
        "Greet the world."
        (interactive)
        (insert "hi"))
    ELISP
  end

  def test_emits_optional_and_rest_parameters
    output = Ruri.compile(<<~RURI, path: "test.ruri")
      function :greet do |name, punctuation = "!", *extra|
        doc "Greet NAME with PUNCTUATION."
        el.message("%s%s", name, punctuation)
      end
    RURI

    assert_includes output, <<~'ELISP'
      (defun greet (ruri--local-name &optional ruri--local-punctuation &rest ruri--local-extra)
        "Greet NAME with PUNCTUATION."
        (unless ruri--local-punctuation
          (setq ruri--local-punctuation "!"))
    ELISP
  end

  def test_emits_lambda_optional_parameters
    output = Ruri.compile(<<~RURI, path: "test.ruri")
      command :scale_cmd do
        interactive
        scale = fn do |value, factor = 2|
          el.identity(value)
        end
        el.identity(scale)
      end
    RURI

    assert_includes output, "(lambda (ruri--local-value &optional ruri--local-factor)"
    assert_includes output, "(unless ruri--local-factor\n          (setq ruri--local-factor 2))"
  end

  def test_emits_command_parameters_and_interactive_spec
    output = Ruri.compile(<<~RURI, path: "test.ruri")
      command :jump_cmd do |location, raw_prefix = nil|
        doc "Jump to LOCATION, honoring the raw prefix argument."
        interactive "P"
        el.message("%s %s", location, raw_prefix)
      end
    RURI

    assert_includes output, <<~'ELISP'
      (defun jump-cmd (ruri--local-location &optional ruri--local-raw-prefix)
        "Jump to LOCATION, honoring the raw prefix argument."
        (interactive "P")
    ELISP
  end

  def test_emits_condition_case
    output = Ruri.compile(<<~RURI, path: "test.ruri")
      function :safe do |a|
        doc "Divide or report."
        begin
          a + 1
        rescue :arith_error => problem
          el.message("%s", el.error_message_string(problem))
        rescue
          el.message("other")
        else
          el.message("ok")
        end
      end
    RURI

    assert_includes output, <<-'ELISP'.chomp
  (let (ruri--local-problem)
    (condition-case ruri--local-problem
      (+ ruri--local-a 1)
      ((arith-error)
        (message "%s"
          (error-message-string ruri--local-problem)))
      ((error)
        (message "other"))
      (:success
        (message "ok"))))
    ELISP
  end
end
