;;; -*- lexical-binding: t; -*-
;;; Generated by ruri 0.9.0 from /Users/mac/projects/ruri/examples/greet.ruri. DO NOT EDIT.

(require 'subr-x)

(defvar greet-name "Emacs"
  "Name used in greetings.")

(defconst greet-version "1.0"
  "Version of the greet package.")

(defcustom greet-style 'plain
  "How greetings are formatted."
  :type 'symbol)

(defun greet-hello ()
  "Say hello to the configured name."
  (interactive)
  (message "Hello, %s!" greet-name))

(defun greet-report ()
  "Report the package configuration."
  (interactive)
  (message "name=%S style=%S version=%S" greet-name greet-style greet-version))

(provide 'greet)
