;;; -*- lexical-binding: t; -*-
;;; Generated by ruri 0.2.0 from /Users/mac/projects/ruri/examples/hello.ruri. DO NOT EDIT.

(defun hello-buffer ()
  (interactive)
  (with-current-buffer "*scratch*"
    (insert "Hello from Ruby syntax!\n")))
