;;; -*- lexical-binding: t; -*-
;;; Generated by ruri 0.10.0 from examples/hello.ruri. DO NOT EDIT.

(defun hello-buffer ()
  (interactive)
  (with-current-buffer "*scratch*"
    (insert "Hello from Ruby syntax!\n")))
