# frozen_string_literal: true

module Ruri
  # Serializes validated internal forms into deterministic, readable
  # Emacs Lisp text. This is the only place source-derived strings become
  # output text, and every such string goes through Ruri::Emitter.quote,
  # so a literal can never contribute Lisp structure.
  class Emitter
    HEADER = ";;; -*- lexical-binding: t; -*-"

    # Escapes special to Emacs Lisp string syntax. Control characters use
    # exactly three octal digits so a following digit can never join the
    # escape. Non-ASCII characters pass through as UTF-8.
    ESCAPES = {
      "\\" => "\\\\",
      "\"" => "\\\"",
      "\n" => "\\n",
      "\t" => "\\t",
      "\r" => "\\r",
      "\f" => "\\f",
      "\e" => "\\e"
    }.freeze

    class << self
      def emit(commands, source_path:)
        new(commands, source_path).emit
      end

      def quote(text)
        escaped = text.each_char.map do |ch|
          ESCAPES[ch] || (ch.ord < 32 || ch.ord == 127 ? format("\\%03o", ch.ord) : ch)
        end.join
        "\"#{escaped}\""
      end
    end

    def initialize(commands, source_path)
      @commands = commands
      @source_path = source_path
    end

    def emit
      out = +"#{HEADER}\n"
      out << ";;; Generated by ruri #{Ruri::VERSION} from #{@source_path}. DO NOT EDIT.\n"
      @commands.each do |command|
        out << "\n"
        out << emit_command(command)
        out << "\n"
      end
      out
    end

    private

    # Closing parens attach to the last line of the form they close.
    def emit_command(command)
      lines = ["(defun #{command.name} ()"]
      command.body.each { |stmt| lines << emit_statement(stmt, 1) }
      lines[-1] += ")" if command.body.any?
      lines.join("\n")
    end

    def emit_statement(stmt, indent)
      pad = "  " * indent
      case stmt
      when Forms::Interactive
        "#{pad}(interactive)"
      when Forms::Insert
        "#{pad}(insert #{Ruri::Emitter.quote(stmt.text)})"
      when Forms::WithCurrentBuffer
        lines = ["#{pad}(with-current-buffer #{Ruri::Emitter.quote(stmt.buffer)}"]
        stmt.body.each { |inner| lines << emit_statement(inner, indent + 1) }
        lines[-1] += ")" if stmt.body.any?
        lines.join("\n")
      else
        raise ArgumentError, "unemittable form: #{stmt.class}"
      end
    end
  end
end
