# frozen_string_literal: true

module Ruri
  # Wraps lowered forms with deterministic generated-file metadata. Lowerer
  # owns Ruri semantics and Elisp::Printer owns Lisp serialization.
  class Emitter
    HEADER = ";;; -*- lexical-binding: t; -*-"

    class << self
      def emit(definitions, source_path:)
        new(definitions, source_path).emit
      end

      # Keep source metadata on one comment line. Unix filenames may contain
      # newlines and control characters, so interpolating a path verbatim can
      # turn metadata into executable Lisp on the following line.
      def comment_text(text)
        text.each_char.map do |ch|
          case ch
          when "\\" then "\\\\"
          when "\n" then "\\n"
          when "\r" then "\\r"
          when "\t" then "\\t"
          else
            ch.ord < 32 || ch.ord == 127 ? format("\\%03o", ch.ord) : ch
          end
        end.join
      end
    end

    def initialize(definitions, source_path)
      @definitions = definitions
      @source_path = source_path
    end

    def emit
      out = +"#{HEADER}\n"
      source = Ruri::Emitter.comment_text(@source_path.to_s)
      out << ";;; Generated by ruri #{Ruri::VERSION} from #{source}. DO NOT EDIT.\n"
      Lowerer.lower(@definitions).each do |form|
        out << "\n"
        out << Elisp::Printer.print(form)
        out << "\n"
      end
      out
    end
  end
end
