# frozen_string_literal: true

require "pathname"

module Ruri
  # Wraps lowered forms with deterministic generated-file metadata. Lowerer
  # owns Ruri semantics and Elisp::Printer owns Lisp serialization.
  class Emitter
    HEADER = ";;; -*- lexical-binding: t; -*-"

    class << self
      def emit(definitions, source_path:)
        new(definitions, source_path).emit
      end

      # Keep source metadata on one comment line. Unix filenames may contain
      # newlines and control characters, so interpolating a path verbatim can
      # turn metadata into executable Lisp on the following line.
      def comment_text(text)
        text.each_char.map do |ch|
          case ch
          when "\\" then "\\\\"
          when "\n" then "\\n"
          when "\r" then "\\r"
          when "\t" then "\\t"
          else
            ch.ord < 32 || ch.ord == 127 ? format("\\%03o", ch.ord) : ch
          end
        end.join
      end
    end

    def initialize(definitions, source_path)
      @definitions = definitions
      @source_path = source_path
    end

    # The header records the source path relative to the working
    # directory when possible, so output does not depend on whether the
    # compiler was invoked with a relative or an absolute path.
    def self.display_path(path)
      # File.realpath resolves symlinked parents (on macOS /var is a link
      # to /private/var), so a path inside the working directory is
      # recognized as such however it was spelled.
      absolute = resolve(path.to_s)
      base = resolve(Dir.pwd)
      relative = relative_path(absolute, base)
      return path.to_s if relative.nil? || relative.start_with?("..")

      relative
    end

    # Returns nil when the two paths share no common root (for example
    # different drives on Windows).
    def self.relative_path(absolute, base)
      Pathname.new(absolute).relative_path_from(Pathname.new(base)).to_s
    rescue ArgumentError
      nil
    end

    def self.resolve(path)
      File.realpath(path)
    rescue SystemCallError
      File.absolute_path(path)
    end

    def emit
      out = +"#{HEADER}\n"
      source = Ruri::Emitter.comment_text(Ruri::Emitter.display_path(@source_path))
      out << ";;; Generated by ruri #{Ruri::VERSION} from #{source}. DO NOT EDIT.\n"
      Lowerer.lower(@definitions).each do |form|
        out << "\n"
        out << Elisp::Printer.print(form)
        out << "\n"
      end
      out
    end
  end
end
